[package]
name = "yelc"
version = "0.1.0"
edition = "2024"
description = "CLI for the Yel DSL compiler"

[lib]
name = "yelc"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "yelc"
path = "src/main.rs"

[dependencies]
yel-core = { path = "../yel-core" }
clap = { version = "4", features = ["derive"] }
anyhow = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
wasmprinter = "0.227"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wit-bindgen = "0.50"

[features]
default = []
